name: w_node
description: Warehouse Inventory Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- БАЗА ДАННЫХ (ОБЛАКО) ---
  # Важно: версия 2.6.1 нужна для работы твоего текущего кода DBService
  postgres: ^2.6.1

  # --- БАЗА ДАННЫХ (ОФЛАЙН) ---
  # Эти две библиотеки нужны для работы без интернета
  sqflite: ^2.4.2
  path: ^1.9.0

  # --- НАСТРОЙКИ И УТИЛИТЫ ---
  shared_preferences: ^2.2.2
  intl: ^0.19.0

  # --- СТАНДАРТНЫЕ ИКОНКИ ---
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.4.0+2
  vibration: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Линтер (проверка кода)
  flutter_lints: ^3.0.0

  # --- ГЕНЕРАТОР ИКОНОК ПРИЛОЖЕНИЯ ---
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Если будешь использовать картинки внутри программы (логотипы),
  # раскомментируй эти строки и создай папку assets:
  # assets:
  #   - assets/

# --- НАСТРОЙКИ ДЛЯ ИКОНКИ ---
# 1. Создай папку assets в корне проекта
# 2. Положи туда картинку icon.png
# 3. Запусти команду: dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21