name: w_node
description: Warehouse Inventory Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.1.5
  flutter_local_notifications: ^17.2.4
  flutter_animate: ^4.5.0
  postgres: ^2.6.4

  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: any 

  shared_preferences: ^2.5.4
  intl: 0.19.0
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  vibration: 3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  # ðŸ”¥ Ð”Ð¾Ð´Ð°Ñ”Ð¼Ð¾ Ð°Ð´Ð°Ð¿Ñ‚Ð¸Ð²Ð½Ñ– ÑˆÐ°Ñ€Ð¸ Ð´Ð»Ñ Android 8+ (Samsung Fix)
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icon.png"
  min_sdk_android: 21